services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    ports:
    - "5453:53/tcp"
    - "5453:53/udp"

  blocky:
    depends_on:
      - unbound
    image: spx01/blocky
    container_name: dns
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./config.yml:/app/config.yml

  blocky-frontend:
    depends_on:
      - blocky
    image: ghcr.io/mozart409/blocky-frontend:latest
    ports:
      - '81:81/tcp'

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_SCHEDULE
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
