services:
  unbound:
      image: pedantic/unbound:latest
      container_name: dns-unbound
      ports:
      - 5354:5353/udp
      - 5354:5353/tcp
      volumes:
        - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
      restart: always
      healthcheck:
        test: drill cloudflare.com || exit 1
        interval: 30s
        timeout: 5s
        retries: 3
        start_period: 60s

  blocky:
    image: spx01/blocky:v0.24
    container_name: dns-blocky
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./blocky/config.yml:/app/config.yml:ro
      - ./blocky/google-ads-whitelist.txt:/app/google-ads-whitelist.txt:ro
    depends_on:
      unbound:
        condition: service_healthy
    restart: always

