upstreams:
  init:
    strategy: fast
  timeout: 10s
  groups:
    default:
      - tcp+udp:192.168.1.4:5354
      - tcp+udp:192.168.1.170:5354
bootstrapDns:
  - upstream: tcp+udp:8.8.8.8

connectIPVersion: v4

filtering:
  queryTypes:
    - AAAA

fqdnOnly:
  enable: true

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    adult:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-only/hosts
  allowlists:
    ads:
      - google-ads-whitelist.txt
  clientGroupsBlock:
    default:
      - ads
  loading:
    downloads:
      timeout: 4m
      attempts: 5
      cooldown: 10s

caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true

customDNS:
  customTTL: 1h
  filterUnmappedTypes: true
  mapping:
    edge.coia.io: 100.65.133.108
    home.coia.io: 100.65.133.108
    cam.coia.io: 100.65.133.108
    music.coia.io: 100.65.133.108
    uptime.coia.io: 100.65.133.108
    network.coia.io: 100.65.133.108
    scrypted.coia.io: 100.65.133.108
    plex.coia.io: 100.65.133.108
    netdata.edge.coia.io: 100.65.133.108
ports:
  dns: 53

log:
  level: warn
  format: json
  timestamp: true
  privacy: true
