upstreams:
  init:
    strategy: fast
  timeout: 10s
  groups:
    default:
      - tcp+udp:192.168.1.4:5354
      - tcp+udp:192.168.1.170:5354
bootstrapDns:
  - upstream: tcp-tls:dns.google:853
    ips:
      - 8.8.8.8
      - 8.8.4.4

connectIPVersion: v4

filtering:
  queryTypes:
    - AAAA

fqdnOnly:
  enable: true

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    adult:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-only/hosts
  allowlists:
    ads:
      - google-ads-whitelist.txt
  clientGroupsBlock:
    default:
      - ads
    192.168.5.0/24:
      - ads
      - adult
    192.168.2.0/24:
      - ads
      - adult
    192.168.3.0/24:
      - ads
      - adult
  loading:
    downloads:
      timeout: 4m
      attempts: 5
      cooldown: 10s

caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true

clientLookup:
  upstream: 192.168.1.1

certFile: /certs/server.crt
keyFile: /certs/server.key

ports:
  dns: 53
  tls: 853
  http: 4000
  dohPath: /dns-query

log:
  level: warn
  format: json
  timestamp: true
  privacy: true
