upstreams:
  init:
    strategy: fast
  timeout: 10s
  groups:
    default:
      - tcp+udp:192.168.1.4:5354
      - tcp+udp:192.168.1.170:5354
bootstrapDns:
  - upstream: tcp+udp:8.8.8.8

connectIPVersion: v4

filtering:
  queryTypes:
    - AAAA

fqdnOnly:
  enable: true

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    adult:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-only/hosts
  allowlists:
    ads:
      - google-ads-whitelist.txt
  clientGroupsBlock:
    default:
      - ads
    192.168.5.0/24:
      - ads
      - adult
    192.168.2.0/24:
      - ads
      - adult
    192.168.3.0/24:
      - ads
      - adult
  loading:
    downloads:
      timeout: 4m
      attempts: 5
      cooldown: 10s

caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true

customDNS:
  customTTL: 1h
  filterUnmappedTypes: true
  mapping:
    edge.coia.io: 192.168.1.84
    home.coia.io: 192.168.1.84
    cam.coia.io: 192.168.1.84
    music.coia.io: 192.168.1.84
    uptime.coia.io: 192.168.1.84
    network.coia.io: 192.168.1.84
    nvr.coia.io: 192.168.1.86
    scrypted.coia.io: 192.168.1.86
    ha.internal.coia.io: 192.168.1.228
    seattle.coia.io: 192.168.1.222
    unifi.coia.io: 192.168.1.1
    dns1.coia.io: 192.168.1.4
    netdata.dns1.coia.io: 192.168.1.4
    ntp1.coia.io: 192.168.1.4
    dns2.coia.io: 192.168.1.170
    netdata.dns2.coia.io: 192.168.1.170
    ntp2.coia.io: 192.168.1.170
    cam.garden.coia.io: 192.168.3.179
    cam-exterior.workshop.coia.io: 192.168.1.223
    cam-exterior.garage.coia.io: 192.168.3.7
    cam.entrance.coia.io: 192.168.3.87
    cam-drive.workshop.coia.io: 192.168.1.247
    cam.doorbell.coia.io: 192.168.3.71
    plex.coia.io: 192.168.1.84
    netdata.edge.coia.io: 192.168.1.84
    netdata.nvr.coia.io: 192.168.1.86
    netdata.race.coia.io: 192.168.6.109
    giomac.coia.io: 192.168.6.48

clientLookup:
  upstream: 192.168.1.1

ports:
  dns: 53
  http: 4000
  dohPath: /dns-query

log:
  level: warn
  format: json
  timestamp: true
  privacy: true
