upstreams:
  init:
    strategy: fast
  timeout: 10s
  groups:
    default:
      - 192.168.1.4:5354

bootstrapDns:
  - upstream: tcp+udp:8.8.8.8

connectIPVersion: v4

filtering:
  queryTypes:
    - AAAA

fqdnOnly:
  enable: true

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  allowlists:
    ads:
      - google-ads-whitelist.txt
  clientGroupsBlock:
    default:
      - ads
  loading:
    downloads:
      timeout: 4m
      attempts: 5
      cooldown: 10s

caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true

customDNS:
  customTTL: 1h
  filterUnmappedTypes: true
  mapping:
    nvr.coia.io: 192.168.6.87
    scrypted.coia.io: 192.168.6.87
    ha.internal.coia.io: 192.168.1.228
    seattle.coia.io: 192.168.1.222
    unifi.coia.io: 192.168.1.1
    dns1.coia.io: 192.168.1.4
    dns2.coia.io: 192.168.1.170
    cam.garden.coia.io: 192.168.3.179
    cam-exterior.workshop.coia.io: 192.168.3.9
    cam-exterior.garage.coia.io: 192.168.3.7
#conditional:
#  fallbackUpstream: false
#  mapping:
   # for reverse DNS lookups of local devices
#    1.168.192.in-addr.arpa: 192.168.1.1
    # for all unqualified hostnames
#    .: 192.168.1.1
#    3.168.192.in-addr.arpa: 192.168.3.1
#    6.168.192.in-addr.arpa: 192.168.6.1

clientLookup:
  upstream: 192.168.1.1

ports:
  dns: 53

log:
  level: warn
  format: text
  timestamp: false
  privacy: true
