forward-zone:
    name: "."
    # Format: IP@PORT#HOSTNAME — no spaces allowed
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 8.8.8.8@853#dns.google
    forward-addr: 8.8.4.4@853#dns.google
    forward-addr: 45.90.28.0@853#fef8fa.dns.nextdns.io
    forward-addr: 45.90.30.0@853#fef8fa.dns.nextdns.io
    forward-addr: 94.140.14.14@853#dns.adguard-dns.com
    forward-addr: 94.140.15.15@853#dns.adguard-dns.com
    forward-sequential: yes
