    # Edge / home services (192.168.1.84)
    local-data: "edge.coia.io. A 192.168.1.84"
    local-data: "home.coia.io. A 192.168.1.84"
    local-data: "cam.coia.io. A 192.168.1.84"
    local-data: "music.coia.io. A 192.168.1.84"
    local-data: "uptime.coia.io. A 192.168.1.84"
    local-data: "network.coia.io. A 192.168.1.84"
    local-data: "plex.coia.io. A 192.168.1.84"
    local-data: "scrypted.coia.io. A 192.168.1.84"
    local-data: "netdata.edge.coia.io. A 192.168.1.84"

    # NVR / Scrypted (192.168.1.86)
    local-data: "nvr.coia.io. A 192.168.1.86"
    local-data: "netdata.nvr.coia.io. A 192.168.1.86"

    # Home Assistant (192.168.1.228)
    local-data: "ha.internal.coia.io. A 192.168.1.228"
    local-data-ptr: "192.168.1.228 ha.internal.coia.io"

    # Seattle (192.168.1.222)
    local-data: "seattle.coia.io. A 192.168.1.222"
    local-data-ptr: "192.168.1.222 seattle.coia.io"

    # UniFi controller (192.168.1.1)
    local-data: "unifi.coia.io. A 192.168.1.1"
    local-data-ptr: "192.168.1.1 unifi.coia.io"

    # DNS1 / NTP1 (192.168.1.4)
    local-data: "dns1.coia.io. A 192.168.1.4"
    local-data: "netdata.dns1.coia.io. A 192.168.1.4"
    local-data: "ntp1.coia.io. A 192.168.1.4"
    local-data-ptr: "192.168.1.4 dns1.coia.io"

    # DNS2 / NTP2 (192.168.1.170)
    local-data: "dns2.coia.io. A 192.168.1.170"
    local-data: "netdata.dns2.coia.io. A 192.168.1.170"
    local-data: "ntp2.coia.io. A 192.168.1.170"
    local-data-ptr: "192.168.1.170 dns2.coia.io"

    # Cameras
    local-data: "cam.garden.coia.io. A 192.168.3.179"
    local-data-ptr: "192.168.3.179 cam.garden.coia.io"
    local-data: "cam-exterior.workshop.coia.io. A 192.168.1.223"
    local-data-ptr: "192.168.1.223 cam-exterior.workshop.coia.io"
    local-data: "cam-exterior.garage.coia.io. A 192.168.3.7"
    local-data-ptr: "192.168.3.7 cam-exterior.garage.coia.io"
    local-data: "cam.entrance.coia.io. A 192.168.3.87"
    local-data-ptr: "192.168.3.87 cam.entrance.coia.io"
    local-data: "cam-drive.workshop.coia.io. A 192.168.1.247"
    local-data-ptr: "192.168.1.247 cam-drive.workshop.coia.io"
    local-data: "cam.doorbell.coia.io. A 192.168.3.71"
    local-data-ptr: "192.168.3.71 cam.doorbell.coia.io"

    # Race server (192.168.6.109)
    local-data: "netdata.race.coia.io. A 192.168.6.109"

    # Gio's Mac (192.168.6.48)
    local-data: "giomac.coia.io. A 192.168.6.48"
    local-data-ptr: "192.168.6.48 giomac.coia.io"
